# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-04 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Date_Of_Joining',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Employee_ID',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Employee_Name',
        ),
        migrations.AddField(
            model_name='employee',
            name='Credential',
            field=models.FileField(default=2, upload_to=employee.models.get_upload_file_name),
            preserve_default=False,
        ),
    ]
