# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-04 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Description',
            field=models.TextField(default=2, max_length=254),
            preserve_default=False,
        ),
    ]
