# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-07 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20160407_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r00', models.CharField(max_length=254)),
                ('r01', models.CharField(max_length=254)),
                ('r02', models.CharField(max_length=254)),
                ('r03', models.CharField(max_length=254)),
                ('r04', models.CharField(max_length=254)),
                ('r05', models.CharField(max_length=254)),
                ('r06', models.CharField(max_length=254)),
                ('r10', models.CharField(max_length=254)),
                ('r11', models.CharField(max_length=254)),
                ('r12', models.CharField(max_length=254)),
                ('r13', models.CharField(max_length=254)),
                ('r14', models.CharField(max_length=254)),
                ('r15', models.CharField(max_length=254)),
                ('r16', models.CharField(max_length=254)),
                ('r20', models.CharField(max_length=254)),
                ('r21', models.CharField(max_length=254)),
                ('r22', models.CharField(max_length=254)),
                ('r23', models.CharField(max_length=254)),
                ('r24', models.CharField(max_length=254)),
                ('r25', models.CharField(max_length=254)),
                ('r26', models.CharField(max_length=254)),
                ('r30', models.CharField(max_length=254)),
                ('r31', models.CharField(max_length=254)),
                ('r32', models.CharField(max_length=254)),
                ('r33', models.CharField(max_length=254)),
                ('r34', models.CharField(max_length=254)),
                ('r35', models.CharField(max_length=254)),
                ('r36', models.CharField(max_length=254)),
                ('r40', models.CharField(max_length=254)),
                ('r41', models.CharField(max_length=254)),
                ('r42', models.CharField(max_length=254)),
                ('r43', models.CharField(max_length=254)),
                ('r44', models.CharField(max_length=254)),
                ('r45', models.CharField(max_length=254)),
                ('r46', models.CharField(max_length=254)),
                ('r50', models.CharField(max_length=254)),
                ('r51', models.CharField(max_length=254)),
                ('r52', models.CharField(max_length=254)),
                ('r53', models.CharField(max_length=254)),
                ('r54', models.CharField(max_length=254)),
                ('r55', models.CharField(max_length=254)),
                ('r56', models.CharField(max_length=254)),
            ],
        ),
    ]
