# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160312175816 on 2016-04-07 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20160403_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicines',
            name='refill',
        ),
        migrations.AddField(
            model_name='medicines',
            name='refill_threshold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
