# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160312175816 on 2016-04-07 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20160407_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='expiry_date',
            field=models.DateField(validators=[inventory.models.validate_Expirydate]),
        ),
    ]
