# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160312175816 on 2016-04-10 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20160407_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicines',
            name='refill_boolean',
            field=models.BooleanField(default=False),
        ),
    ]
