# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-31 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_auto_20160310_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='PatientId',
            field=models.CharField(max_length=254),
        ),
    ]
