# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-07 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_remove_patient_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Issued',
            field=models.BooleanField(default=False),
        ),
    ]
